language: go

go:
  - 1.1
  - 1.2
  - release
  - tip

install: make get-deps

before_install:
  - mv $HOME/gopath/src/github.com/typecho-app-store/typecho-app-store $HOME/gopath/src/
  - cd $HOME/gopath/src/typecho-app-store